const projectsObjs = [
  {
    name: "Apply Guy",
    description: [
      "<em class=\"highlight2\">Friendship ended with spreadsheets. Now Apply Guy is my best friend.</em>",
      "I wanted a way to keep track of my and my partner's job hunt progress that wasn't just a boring spreadsheet, so this <em class=\"highlight2\">CRUD</em> application was born.",
      "Frontend built with <em class=\"highlight2\">Svelte</em>; backend (authentication and database) served by <em class=\"highlight2\">Firebase</em>."
    ],
    demo: "https://apply-guy.netlify.app/",
    source: "https://github.com/jasmwebb/apply-guy",
    thumbnail: "/assets/thumbs/applyguythumb.png",
    tags: [
      "Svelte",
      "Firebase",
      "JAMstack"
    ]
  },
  {
    name: "Advent of Code 2020",
    description: [
      "My first year participating in Advent of Code; all of my solutions were written in <em class=\"highlight2\">Python</em>.",
      "This was a fun challenge in problem solving, utilizing appropriate data structures, implementing test suites (although I didn't think to do that until the last few days), and catching up. Lots of catching up.",
      "I look forward to saving Christmas all over again next year."
    ],
    demo: null,
    source: "https://github.com/jasmwebb/advent-of-code",
    thumbnail: "/assets/thumbs/aoc2020thumb.png",
    tags: [
      "Python"
    ]
  },
  {
    name: "Herowatch Scraper",
    description: [
      "Grabs the heroes' data from the Overwatch wiki, then writes it all to a single JSON file. This was mainly an exercise in <em class=\"highlight2\">regular expressions</em>.",
      "Written in <em class=\"highlight2\">Python</em> and manually run from the command line.",
      "Demo link leads to the generated JSON file; best viewed with a JSON formatting browser extension installed."
    ],
    demo: "https://raw.githubusercontent.com/jasmwebb/herowatch-scraper/main/heroes.json",
    source: "https://github.com/jasmwebb/herowatch-scraper",
    thumbnail: "/assets/thumbs/herowatchthumb.png",
    tags: [
      "Python"
    ]
  },
  {
    name: "Mailming",
    description: [
      "This is a \"private\" blog made to emulate snail mail between two people with a vague 00s aesthetic.",
      "The idea is to facilitate <em class=\"highlight2\">indirect</em> communication in a second language that is not native to me, which rules out email and other direct messaging media. No notifications, no read receipts, no pressure to write quickly; just conversation.",
      "Generated by <em class=\"highlight2\">Eleventy</em>. Deployed on <em class=\"highlight2\">Netlify</em> with <em class=\"highlight2\">Netlify CMS</em>. No demo link to maintain a smidgen of \"privacy.\""
    ],
    demo: null,
    source: "https://github.com/jasmwebb/mailming",
    thumbnail: "/assets/thumbs/mailmingthumb.gif",
    tags: [
      "Eleventy",
      "Sass",
      "JAMstack"
    ]
  },
  {
    name: "Counting Rows",
    description: [
      "A tool to keep track of the number of rows I've knitted of various charts and/or patterns.",
      "Similar extant tools have intrusive ads and/or too many unnecessary features for my liking. Since knitting is already complicated enough, I sought to make something barebones.",
      "Each counter is saved to and loaded from <em class=\"highlight2\">localStorage</em> for extra simplicity.",
      "Made with <em class=\"highlight2\">Svelte</em> and <em class=\"highlight2\">TailwindCSS</em>."
    ],
    demo: "https://countingrows.netlify.app/",
    source: "https://github.com/jasmwebb/counting-rows",
    thumbnail: "/assets/thumbs/countingrowsthumb.png",
    tags: [
      "Svelte",
      "TailwindCSS",
      "JAMstack"
    ]
  },
  {
    name: "K-STAN (code name)",
    description: [
      "The simplest analogy would be <em class=\"highlight2\">Yelp for K-Pop Stans</em>.",
      "A one-stop resource to locate and bookmark cafes, restaurants, etc. associated with popular Korean Pop idols. K-Pop fans who are planning a trip to Korea have a covenient way to access this information in one place, as opposed to having to piece it together from several fan sites, the number of which grows exponentially by the number of groups the fan supports.",
      "This is a collaborative project that currently has no code; but we are designing K-STAN as a <em class=\"highlight2\">JAMstack</em> application."
    ],
    demo: "https://www.figma.com/file/lvdKpHHm7cok0fVFtGHdEM/Prototypes?node-id=0%3A1",
    source: null,
    thumbnail: "/assets/thumbs/kstanframes.png",
    tags: [
      "Figma",
      "JAMstack"
    ]
  },
  {
    name: "Kumho (금호) Compiler",
    description: [
      "Prototype enterprise software written in <em class=\"highlight2\">Python</em> for a friend’s business. It automates the process of combing through a large volume of files for data and synthesizing that data into Microsoft Excel tables and graphs.",
      "<em class='highlight'>Note:</em> The above thumbnail shows all the prompts and processes, however, since a data set is not specified in prompt #2, this particular execution did nothing."
    ],
    demo: null,
    source: "https://github.com/jasmwebb/kumho-compiler",
    thumbnail: "/assets/thumbs/kumhocompilerthumb.png",
    tags: [
      "Python"
    ]
  },
  {
    name: "Kamatimer",
    description: [
      "Just a pomodoro timer made with vanilla <em class=\"highlight2\">JavaScript</em> and <em class=\"highlight2\">Sass</em>."
    ],
    demo: "https://jasmwebb.github.io/kamatimer/",
    source: "https://github.com/jasmwebb/kamatimer",
    thumbnail: "/assets/thumbs/kamatimerthumb.png",
    tags: [
      "JavaScript",
      "Sass",
      "JAMstack"
    ]
  },
  {
    name: "Portfolio",
    description: [
      "This very portfolio was made with <em class=\"highlight2\" style='font-style: normal;'>♡</em> with vanilla <em class=\"highlight2\">JavaScript</em> and <em class=\"highlight2\">Sass</em>."
    ],
    demo: null,
    source: "https://github.com/jasmwebb/jasmwebbdev",
    thumbnail: "/assets/ghost_bear_t.png",
    tags: [
      "JavaScript",
      "Sass",
      "JAMstack"
    ]
  }
];

export default projectsObjs;
